import type { Project } from "@/features/projects/types";

export const mockProject = {
	projectId: 1,
	projectCode: "PRJ001",
	name: "A工場建設プロジェクト",
	businessUnitCode: "BU001",
	businessUnitName: "エンジニアリング事業部",
	projectTypeCode: "PT001",
	projectTypeName: "設計",
	startYearMonth: "202504",
	totalManhour: 12000,
	status: "confirmed",
	durationMonths: 24,
	fiscalYear: 2025,
	nickname: null,
	customerName: "サンプル株式会社",
	orderNumber: "ORD-001",
	calculationBasis: null,
	remarks: null,
	region: "関東",
	createdAt: "2025-01-01T00:00:00Z",
	updatedAt: "2025-01-01T00:00:00Z",
	cases: [{ projectCaseId: 1, caseName: "標準", isPrimary: true }],
} satisfies Project;

export const mockProjects: Project[] = [
	mockProject,
	{
		projectId: 2,
		projectCode: "PRJ002",
		name: "B工場改修プロジェクト",
		businessUnitCode: "BU001",
		businessUnitName: "エンジニアリング事業部",
		projectTypeCode: "PT002",
		projectTypeName: "施工管理",
		startYearMonth: "202507",
		totalManhour: 8000,
		status: "planning",
		durationMonths: 12,
		fiscalYear: 2025,
		nickname: "B工場",
		customerName: null,
		orderNumber: null,
		calculationBasis: null,
		remarks: null,
		region: null,
		createdAt: "2025-02-01T00:00:00Z",
		updatedAt: "2025-02-01T00:00:00Z",
		cases: [{ projectCaseId: 2, caseName: "標準", isPrimary: true }],
	},
	{
		projectId: 3,
		projectCode: "PRJ003",
		name: "C施設メンテナンス",
		businessUnitCode: "BU002",
		businessUnitName: "プラント事業部",
		projectTypeCode: null,
		projectTypeName: null,
		startYearMonth: "202601",
		totalManhour: 3000,
		status: "planning",
		durationMonths: 6,
		fiscalYear: null,
		nickname: null,
		customerName: null,
		orderNumber: null,
		calculationBasis: null,
		remarks: null,
		region: null,
		createdAt: "2025-03-01T00:00:00Z",
		updatedAt: "2025-03-01T00:00:00Z",
		cases: [{ projectCaseId: 3, caseName: "標準", isPrimary: true }],
	},
];
