/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkloadIndexRouteImport } from './routes/workload/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsStandardEffortsIndexRouteImport } from './routes/projects/standard-efforts/index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as MasterWorkTypesIndexRouteImport } from './routes/master/work-types/index'
import { Route as MasterProjectTypesIndexRouteImport } from './routes/master/project-types/index'
import { Route as MasterIndirectWorkCasesIndexRouteImport } from './routes/master/indirect-work-cases/index'
import { Route as MasterIndirectCapacitySettingsIndexRouteImport } from './routes/master/indirect-capacity-settings/index'
import { Route as MasterHeadcountPlansIndexRouteImport } from './routes/master/headcount-plans/index'
import { Route as MasterCapacityScenariosIndexRouteImport } from './routes/master/capacity-scenarios/index'
import { Route as MasterBusinessUnitsIndexRouteImport } from './routes/master/business-units/index'
import { Route as IndirectSimulationIndexRouteImport } from './routes/indirect/simulation/index'
import { Route as ProjectsStandardEffortsNewRouteImport } from './routes/projects/standard-efforts/new'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects/$projectId/edit'
import { Route as ProjectsStandardEffortsStandardEffortIdIndexRouteImport } from './routes/projects/standard-efforts/$standardEffortId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkloadIndexRoute = WorkloadIndexRouteImport.update({
  id: '/workload/',
  path: '/workload/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/workload/index.lazy').then((d) => d.Route),
)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsStandardEffortsIndexRoute =
  ProjectsStandardEffortsIndexRouteImport.update({
    id: '/projects/standard-efforts/',
    path: '/projects/standard-efforts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterWorkTypesIndexRoute = MasterWorkTypesIndexRouteImport.update({
  id: '/master/work-types/',
  path: '/master/work-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterProjectTypesIndexRoute = MasterProjectTypesIndexRouteImport.update({
  id: '/master/project-types/',
  path: '/master/project-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndirectWorkCasesIndexRoute =
  MasterIndirectWorkCasesIndexRouteImport.update({
    id: '/master/indirect-work-cases/',
    path: '/master/indirect-work-cases/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/master/indirect-work-cases/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MasterIndirectCapacitySettingsIndexRoute =
  MasterIndirectCapacitySettingsIndexRouteImport.update({
    id: '/master/indirect-capacity-settings/',
    path: '/master/indirect-capacity-settings/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/master/indirect-capacity-settings/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MasterHeadcountPlansIndexRoute =
  MasterHeadcountPlansIndexRouteImport.update({
    id: '/master/headcount-plans/',
    path: '/master/headcount-plans/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/master/headcount-plans/index.lazy').then((d) => d.Route),
  )
const MasterCapacityScenariosIndexRoute =
  MasterCapacityScenariosIndexRouteImport.update({
    id: '/master/capacity-scenarios/',
    path: '/master/capacity-scenarios/',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/master/capacity-scenarios/index.lazy').then(
      (d) => d.Route,
    ),
  )
const MasterBusinessUnitsIndexRoute =
  MasterBusinessUnitsIndexRouteImport.update({
    id: '/master/business-units/',
    path: '/master/business-units/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndirectSimulationIndexRoute = IndirectSimulationIndexRouteImport.update({
  id: '/indirect/simulation/',
  path: '/indirect/simulation/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/indirect/simulation/index.lazy').then((d) => d.Route),
)
const ProjectsStandardEffortsNewRoute =
  ProjectsStandardEffortsNewRouteImport.update({
    id: '/projects/standard-efforts/new',
    path: '/projects/standard-efforts/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/projects/$projectId/edit',
  path: '/projects/$projectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsStandardEffortsStandardEffortIdIndexRoute =
  ProjectsStandardEffortsStandardEffortIdIndexRouteImport.update({
    id: '/projects/standard-efforts/$standardEffortId/',
    path: '/projects/standard-efforts/$standardEffortId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/workload/': typeof WorkloadIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/standard-efforts/new': typeof ProjectsStandardEffortsNewRoute
  '/indirect/simulation/': typeof IndirectSimulationIndexRoute
  '/master/business-units/': typeof MasterBusinessUnitsIndexRoute
  '/master/capacity-scenarios/': typeof MasterCapacityScenariosIndexRoute
  '/master/headcount-plans/': typeof MasterHeadcountPlansIndexRoute
  '/master/indirect-capacity-settings/': typeof MasterIndirectCapacitySettingsIndexRoute
  '/master/indirect-work-cases/': typeof MasterIndirectWorkCasesIndexRoute
  '/master/project-types/': typeof MasterProjectTypesIndexRoute
  '/master/work-types/': typeof MasterWorkTypesIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/standard-efforts/': typeof ProjectsStandardEffortsIndexRoute
  '/projects/standard-efforts/$standardEffortId/': typeof ProjectsStandardEffortsStandardEffortIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/workload': typeof WorkloadIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/standard-efforts/new': typeof ProjectsStandardEffortsNewRoute
  '/indirect/simulation': typeof IndirectSimulationIndexRoute
  '/master/business-units': typeof MasterBusinessUnitsIndexRoute
  '/master/capacity-scenarios': typeof MasterCapacityScenariosIndexRoute
  '/master/headcount-plans': typeof MasterHeadcountPlansIndexRoute
  '/master/indirect-capacity-settings': typeof MasterIndirectCapacitySettingsIndexRoute
  '/master/indirect-work-cases': typeof MasterIndirectWorkCasesIndexRoute
  '/master/project-types': typeof MasterProjectTypesIndexRoute
  '/master/work-types': typeof MasterWorkTypesIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/standard-efforts': typeof ProjectsStandardEffortsIndexRoute
  '/projects/standard-efforts/$standardEffortId': typeof ProjectsStandardEffortsStandardEffortIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/workload/': typeof WorkloadIndexRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/standard-efforts/new': typeof ProjectsStandardEffortsNewRoute
  '/indirect/simulation/': typeof IndirectSimulationIndexRoute
  '/master/business-units/': typeof MasterBusinessUnitsIndexRoute
  '/master/capacity-scenarios/': typeof MasterCapacityScenariosIndexRoute
  '/master/headcount-plans/': typeof MasterHeadcountPlansIndexRoute
  '/master/indirect-capacity-settings/': typeof MasterIndirectCapacitySettingsIndexRoute
  '/master/indirect-work-cases/': typeof MasterIndirectWorkCasesIndexRoute
  '/master/project-types/': typeof MasterProjectTypesIndexRoute
  '/master/work-types/': typeof MasterWorkTypesIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/standard-efforts/': typeof ProjectsStandardEffortsIndexRoute
  '/projects/standard-efforts/$standardEffortId/': typeof ProjectsStandardEffortsStandardEffortIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/new'
    | '/projects/'
    | '/workload/'
    | '/projects/$projectId/edit'
    | '/projects/standard-efforts/new'
    | '/indirect/simulation/'
    | '/master/business-units/'
    | '/master/capacity-scenarios/'
    | '/master/headcount-plans/'
    | '/master/indirect-capacity-settings/'
    | '/master/indirect-work-cases/'
    | '/master/project-types/'
    | '/master/work-types/'
    | '/projects/$projectId/'
    | '/projects/standard-efforts/'
    | '/projects/standard-efforts/$standardEffortId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/new'
    | '/projects'
    | '/workload'
    | '/projects/$projectId/edit'
    | '/projects/standard-efforts/new'
    | '/indirect/simulation'
    | '/master/business-units'
    | '/master/capacity-scenarios'
    | '/master/headcount-plans'
    | '/master/indirect-capacity-settings'
    | '/master/indirect-work-cases'
    | '/master/project-types'
    | '/master/work-types'
    | '/projects/$projectId'
    | '/projects/standard-efforts'
    | '/projects/standard-efforts/$standardEffortId'
  id:
    | '__root__'
    | '/'
    | '/projects/new'
    | '/projects/'
    | '/workload/'
    | '/projects/$projectId/edit'
    | '/projects/standard-efforts/new'
    | '/indirect/simulation/'
    | '/master/business-units/'
    | '/master/capacity-scenarios/'
    | '/master/headcount-plans/'
    | '/master/indirect-capacity-settings/'
    | '/master/indirect-work-cases/'
    | '/master/project-types/'
    | '/master/work-types/'
    | '/projects/$projectId/'
    | '/projects/standard-efforts/'
    | '/projects/standard-efforts/$standardEffortId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  WorkloadIndexRoute: typeof WorkloadIndexRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
  ProjectsStandardEffortsNewRoute: typeof ProjectsStandardEffortsNewRoute
  IndirectSimulationIndexRoute: typeof IndirectSimulationIndexRoute
  MasterBusinessUnitsIndexRoute: typeof MasterBusinessUnitsIndexRoute
  MasterCapacityScenariosIndexRoute: typeof MasterCapacityScenariosIndexRoute
  MasterHeadcountPlansIndexRoute: typeof MasterHeadcountPlansIndexRoute
  MasterIndirectCapacitySettingsIndexRoute: typeof MasterIndirectCapacitySettingsIndexRoute
  MasterIndirectWorkCasesIndexRoute: typeof MasterIndirectWorkCasesIndexRoute
  MasterProjectTypesIndexRoute: typeof MasterProjectTypesIndexRoute
  MasterWorkTypesIndexRoute: typeof MasterWorkTypesIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsStandardEffortsIndexRoute: typeof ProjectsStandardEffortsIndexRoute
  ProjectsStandardEffortsStandardEffortIdIndexRoute: typeof ProjectsStandardEffortsStandardEffortIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workload/': {
      id: '/workload/'
      path: '/workload'
      fullPath: '/workload/'
      preLoaderRoute: typeof WorkloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/standard-efforts/': {
      id: '/projects/standard-efforts/'
      path: '/projects/standard-efforts'
      fullPath: '/projects/standard-efforts/'
      preLoaderRoute: typeof ProjectsStandardEffortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/work-types/': {
      id: '/master/work-types/'
      path: '/master/work-types'
      fullPath: '/master/work-types/'
      preLoaderRoute: typeof MasterWorkTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/project-types/': {
      id: '/master/project-types/'
      path: '/master/project-types'
      fullPath: '/master/project-types/'
      preLoaderRoute: typeof MasterProjectTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/indirect-work-cases/': {
      id: '/master/indirect-work-cases/'
      path: '/master/indirect-work-cases'
      fullPath: '/master/indirect-work-cases/'
      preLoaderRoute: typeof MasterIndirectWorkCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/indirect-capacity-settings/': {
      id: '/master/indirect-capacity-settings/'
      path: '/master/indirect-capacity-settings'
      fullPath: '/master/indirect-capacity-settings/'
      preLoaderRoute: typeof MasterIndirectCapacitySettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/headcount-plans/': {
      id: '/master/headcount-plans/'
      path: '/master/headcount-plans'
      fullPath: '/master/headcount-plans/'
      preLoaderRoute: typeof MasterHeadcountPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/capacity-scenarios/': {
      id: '/master/capacity-scenarios/'
      path: '/master/capacity-scenarios'
      fullPath: '/master/capacity-scenarios/'
      preLoaderRoute: typeof MasterCapacityScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/business-units/': {
      id: '/master/business-units/'
      path: '/master/business-units'
      fullPath: '/master/business-units/'
      preLoaderRoute: typeof MasterBusinessUnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indirect/simulation/': {
      id: '/indirect/simulation/'
      path: '/indirect/simulation'
      fullPath: '/indirect/simulation/'
      preLoaderRoute: typeof IndirectSimulationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/standard-efforts/new': {
      id: '/projects/standard-efforts/new'
      path: '/projects/standard-efforts/new'
      fullPath: '/projects/standard-efforts/new'
      preLoaderRoute: typeof ProjectsStandardEffortsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/standard-efforts/$standardEffortId/': {
      id: '/projects/standard-efforts/$standardEffortId/'
      path: '/projects/standard-efforts/$standardEffortId'
      fullPath: '/projects/standard-efforts/$standardEffortId/'
      preLoaderRoute: typeof ProjectsStandardEffortsStandardEffortIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  WorkloadIndexRoute: WorkloadIndexRoute,
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
  ProjectsStandardEffortsNewRoute: ProjectsStandardEffortsNewRoute,
  IndirectSimulationIndexRoute: IndirectSimulationIndexRoute,
  MasterBusinessUnitsIndexRoute: MasterBusinessUnitsIndexRoute,
  MasterCapacityScenariosIndexRoute: MasterCapacityScenariosIndexRoute,
  MasterHeadcountPlansIndexRoute: MasterHeadcountPlansIndexRoute,
  MasterIndirectCapacitySettingsIndexRoute:
    MasterIndirectCapacitySettingsIndexRoute,
  MasterIndirectWorkCasesIndexRoute: MasterIndirectWorkCasesIndexRoute,
  MasterProjectTypesIndexRoute: MasterProjectTypesIndexRoute,
  MasterWorkTypesIndexRoute: MasterWorkTypesIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsStandardEffortsIndexRoute: ProjectsStandardEffortsIndexRoute,
  ProjectsStandardEffortsStandardEffortIdIndexRoute:
    ProjectsStandardEffortsStandardEffortIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
