/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterBusinessUnitsIndexRouteImport } from './routes/master/business-units/index'
import { Route as MasterBusinessUnitsNewRouteImport } from './routes/master/business-units/new'
import { Route as MasterBusinessUnitsBusinessUnitCodeIndexRouteImport } from './routes/master/business-units/$businessUnitCode/index'
import { Route as MasterBusinessUnitsBusinessUnitCodeEditRouteImport } from './routes/master/business-units/$businessUnitCode/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterBusinessUnitsIndexRoute =
  MasterBusinessUnitsIndexRouteImport.update({
    id: '/master/business-units/',
    path: '/master/business-units/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterBusinessUnitsNewRoute = MasterBusinessUnitsNewRouteImport.update({
  id: '/master/business-units/new',
  path: '/master/business-units/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterBusinessUnitsBusinessUnitCodeIndexRoute =
  MasterBusinessUnitsBusinessUnitCodeIndexRouteImport.update({
    id: '/master/business-units/$businessUnitCode/',
    path: '/master/business-units/$businessUnitCode/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterBusinessUnitsBusinessUnitCodeEditRoute =
  MasterBusinessUnitsBusinessUnitCodeEditRouteImport.update({
    id: '/master/business-units/$businessUnitCode/edit',
    path: '/master/business-units/$businessUnitCode/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/master/business-units/new': typeof MasterBusinessUnitsNewRoute
  '/master/business-units/': typeof MasterBusinessUnitsIndexRoute
  '/master/business-units/$businessUnitCode/edit': typeof MasterBusinessUnitsBusinessUnitCodeEditRoute
  '/master/business-units/$businessUnitCode/': typeof MasterBusinessUnitsBusinessUnitCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/master/business-units/new': typeof MasterBusinessUnitsNewRoute
  '/master/business-units': typeof MasterBusinessUnitsIndexRoute
  '/master/business-units/$businessUnitCode/edit': typeof MasterBusinessUnitsBusinessUnitCodeEditRoute
  '/master/business-units/$businessUnitCode': typeof MasterBusinessUnitsBusinessUnitCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/master/business-units/new': typeof MasterBusinessUnitsNewRoute
  '/master/business-units/': typeof MasterBusinessUnitsIndexRoute
  '/master/business-units/$businessUnitCode/edit': typeof MasterBusinessUnitsBusinessUnitCodeEditRoute
  '/master/business-units/$businessUnitCode/': typeof MasterBusinessUnitsBusinessUnitCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/master/business-units/new'
    | '/master/business-units/'
    | '/master/business-units/$businessUnitCode/edit'
    | '/master/business-units/$businessUnitCode/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/master/business-units/new'
    | '/master/business-units'
    | '/master/business-units/$businessUnitCode/edit'
    | '/master/business-units/$businessUnitCode'
  id:
    | '__root__'
    | '/'
    | '/master/business-units/new'
    | '/master/business-units/'
    | '/master/business-units/$businessUnitCode/edit'
    | '/master/business-units/$businessUnitCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasterBusinessUnitsNewRoute: typeof MasterBusinessUnitsNewRoute
  MasterBusinessUnitsIndexRoute: typeof MasterBusinessUnitsIndexRoute
  MasterBusinessUnitsBusinessUnitCodeEditRoute: typeof MasterBusinessUnitsBusinessUnitCodeEditRoute
  MasterBusinessUnitsBusinessUnitCodeIndexRoute: typeof MasterBusinessUnitsBusinessUnitCodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/business-units/': {
      id: '/master/business-units/'
      path: '/master/business-units'
      fullPath: '/master/business-units/'
      preLoaderRoute: typeof MasterBusinessUnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/business-units/new': {
      id: '/master/business-units/new'
      path: '/master/business-units/new'
      fullPath: '/master/business-units/new'
      preLoaderRoute: typeof MasterBusinessUnitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/business-units/$businessUnitCode/': {
      id: '/master/business-units/$businessUnitCode/'
      path: '/master/business-units/$businessUnitCode'
      fullPath: '/master/business-units/$businessUnitCode/'
      preLoaderRoute: typeof MasterBusinessUnitsBusinessUnitCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/business-units/$businessUnitCode/edit': {
      id: '/master/business-units/$businessUnitCode/edit'
      path: '/master/business-units/$businessUnitCode/edit'
      fullPath: '/master/business-units/$businessUnitCode/edit'
      preLoaderRoute: typeof MasterBusinessUnitsBusinessUnitCodeEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasterBusinessUnitsNewRoute: MasterBusinessUnitsNewRoute,
  MasterBusinessUnitsIndexRoute: MasterBusinessUnitsIndexRoute,
  MasterBusinessUnitsBusinessUnitCodeEditRoute:
    MasterBusinessUnitsBusinessUnitCodeEditRoute,
  MasterBusinessUnitsBusinessUnitCodeIndexRoute:
    MasterBusinessUnitsBusinessUnitCodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
